import { Inter } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import TanstackReactQueryProvider from "@/Providers/TanstackReactQueryProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="w-screen h-screen">
				<TanstackReactQueryProvider>
					{children}
					<SpeedInsights />
				</TanstackReactQueryProvider>
			</body>
		</html>
	);
}
